### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by Ru-Van** [Royalvice/DocDiff#3]
Can you please add inference time information for different configurations and video cards?

**Comment by Royalvice** [comment]
For the network under the default `conf.yml` configuration, inferring one million pixels on a single 3090 takes about 5 seconds, sampling 100 times. I haven't conducted more comprehensive experiments on inference times. FLOPs and MACC haven't been calculated, but since the network structure of DocDiff is a general Unet, I believe there are many methods for calculation and testing available on the Internet.
