### ISSUE TITLE
Cannot find the Document Deblurring Dataset

### ISSUE THREAD

**Issue by LonglongaaaGo** [Royalvice/DocDiff#33]
Hi @Royalvice 
Thank you so much for your awesome work!
Recently, I tried to train your method on the Document Deblurring Dataset.
However, I cannot find the source dataset from this paper[12].
Could you help with this problem, share it with me.
I will cite your paper.
Thanks!

[12] Michal Hradiš, Jan Kotera, Pavel Zemcık, and Filip Šroubek. 2015. Convolutional neural networks for direct text deblurring. In Proceedings of BMVC, Vol. 10

**Comment by Royalvice** [comment]
Thank you for your interest in our work and your willingness to cite it. The original website of the dataset is https://www.fit.vut.cz/person/ihradis/public/CNN-Deblur/. However, I have found that the URL is no longer accessible. Since we also do not have a backup of this dataset, you will need to search the internet to see if there is a backup available.

**Comment by LonglongaaaGo** [comment]
Hi @Royalvice 
thanks, that is what I mentioned the problem.
So, yeah, otherwise it is hard to compare.
If you or anyone can try to find that, I would really appreciate it!

My email is wanglongl@mun.ca.
Thanks!
